### ISSUE TITLE
feature request: hash to confirm completion

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/ims-tutorials#159]
I would love to have any way of verifying that students completed these, even something as simple as this. 

I would be cool too if there was a random [nonce](https://en.wikipedia.org/wiki/Cryptographic_nonce) (? I think I am using this term correctly?) appended, to discourage rampant cheating. For example, if the correct hash for completing the tutorial is:

536c43f3fe936e0804cc5e3b363d2279

Then have the thing randomly generate, say, a four-character hash that can be appended. Then student A will see:

536c43f3fe936e0804cc5e3b363d2279af83

and student B will see:

536c43f3fe936e0804cc5e3b363d22797b2c

That way, I'll still be able to tell that they did it by verifying the first part of the hash, but then if they cheat and text the hash to another student I will know.

**Comment by mine-cetinkaya-rundel** [comment]
Happy to add hash generation to the tutorials. How does the following generic prompt look?

<img width="1532" alt="Screen Shot 2022-09-14 at 12 29 31 AM" src="https://user-images.githubusercontent.com/5965649/190059881-dca579f1-3a9e-4e35-ac41-0a036ed7d78c.png">

And I'm guessing you'd want `strip_output = TRUE` since the hashes can be quite long -- too long to paste into a form. See https://rundel.github.io/learnrhash/reference/learnr_elements.html for more on that.

As for adding a "nonce", I think that would have to be implemented in learnrhash and then we can use a version of the functions that implements the output. I'm not sure if that's in scope for learnrhash, but I assume it might be. Tagging @rundel to chime in on that.

**Comment by beanumber** [comment]
That sounds great. I don't actually really care about checking the answers. I'd just like to be able to at least sort of verify that they did it.

**Comment by rundel** [comment]
An idea that comes to mind is to modify / extend the `encoder_ui()` to have an option to include an enter your name / id field (with modifiable text) before the generate button and require an entry before allowing generation to occur. Given how the encoding / hashing is done any small change to the input(s) should comopletely change the hash and make them unique.

**Comment by mamcisaac** [comment]
#192 creates the following "Submit" page for all existing tutorials: 

<img width="1292" alt="Screenshot 2023-07-19 at 8 43 19 AM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/55292798/35090dff-5a69-4796-85ad-57a9eb2e9949">

This hash can be decoded to something that looks like the following: 
<img width="1077" alt="Screenshot 2023-07-19 at 8 45 18 AM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/55292798/85ea4eea-2b2d-4277-94ab-32eef782fc53">

This code requires students to enter a name and ID before generating the hash and encodes that information in the hash as a new "identifier" type. 

Note that these "identifier" answers could be used to check the submitted names and IDs in an effort to track student progress (e.g., for participation marks).

**Comment by npaterno** [comment]
Issue closed with PR 192
