### ISSUE TITLE
hint displayed by default - hint correction - could not find answer to question

### ISSUE THREAD

**Issue by ghmorrison** [OpenIntroStat/ims-tutorials#170]
[Tutorial 1 - Lesson 1: Language of data](https://openintro.shinyapps.io/ims-01-data-01/)
Starting with Filtering based on a factor under Categorical data in R: factors: The fist hint is displayed by default in all the practice problems

Under Visualizing numerical data: The first hint is still displaying by default. 
I believe factor(spam) is wrong
ggplot(email50, aes(x = num_char, y = exclaim_mess, color = factor(spam))) +
  geom_point()
  
factor does not appear to change 0, 1 to no, yes. if_else(spam == 1, "yes",  "no") will.

Could not find answer to "Based on the plot, does there appear to be a relationship between these variables?" I assume the answer is no but  it would be very helpful to have this and future questions answered.

They seemed related but should I have asked the separately?
George

**Comment by npaterno** [comment]
Hi George, 

Starting each exercise with the first hint displayed by default is intentional. These tutorials were designed under the assumption that the user has no R experience. As such, it was decided to start off each exercise with a framework to build the solution on. 

In regards to the "factor(spam)" concern, you are correct that it does not _change_ 0, 1 to no, yes. The purpose for that piece of code is to make R treat that variable as if it were no/yes _without changing_ the data set. 

You are also correct that the answer to the last question is "no". I will pass along your request to have answers to these types of questions posted. 

Best, 
~Nick
