### ISSUE TITLE
02-02-lesson

### ISSUE THREAD

**Issue by petzi53** [OpenIntroStat/ims-tutorials#49]
The explanation of the `cars` dataset in lesson 2 of chapter 2 (at the beginning after the first subheader) refers to `int` and `dbl` variables. In the dataset itself, students see only `dbl` variables. Except for `eng_size` they are actually all integers but loaded in the setup chunk with `read_csv`as `dbl`.

A simple change in the text is perhaps not advisable because one of the aims of this part is to explain the difference between integers and floating points. Another solution would be to change the datatype in the setup chunk. Even if this is not very practicable as, during calculation, R computes with doubles anyway, I would suggest this kind of solution from an educational perspective.

If you agree, I could prepare a PR.

**Comment by atheobold** [comment]
@petzi53 -- You are correct, the behaviour of `read_csv()` parsing integers has changed since this tutorial was last revised. I agree that it is a good educational tool to teach students about the differences between integers and doubles. I think changing the data types used for `read_csv()` in the set-up chunk is a great idea!
